### ISSUE TITLE
No admiral mode or monitor commands

### ISSUE THREAD

**Issue by hsnewman** [rumour/jtrek#1]
I can't enter any admiral mode commands (control + A). It instead does the klingon message...(the ship is a Q class, but I notice that there are multiple records for the shipname...is that normal?)

Also, on the server, I can't get response from any commands i enter there...such as shutdown.

Other than that, all is working....

**Comment by rumour** [comment]
If you have multiple 'live' ships with the same name, I'm not sure which one it would actually login.  When you hit 'ESC-s' in-game does the Class value for your admiral vessel show 'Q'?  Make sure that all of the non-Q records for your ship have 'ship_alive' set to 0, and see if that resolves the problem.

How are you running the server?  (operating system -- windows/linux/?, in a shell/command window/IDE? using backgrounding 'screen' type command, or just running it 'live'?)  I just fired it up in a java IDE and in the console window typed 'show players' + Enter key, and get a list of active ships.  Valid commands are: 'show players', 'remove unknown', 'shutdown', 'reboot', and 'show playerids' and are case-insensitive.

**Comment by hsnewman** [comment]
I'm in Linux command line currently under Kubuntu 13.10.  I don't know what
I did, but its now working.

I'm using the command line to build the source. I'd like to use an IDE but
don't know how...any help there would be great.  I have eclipse, gradle and
groovy installed, I just don't know how to bring the project into eclipse
to compile.

Thanks much,

Harris

**Comment by rumour** [comment]
I've been away from Eclipse for awhile, but I downloaded the current version, 4.3.1 for Java developers to see what the process would be.

When launching, I pointed the Eclipse workspace to the default (c:\users\jay\workspace for me). I clicked File -> New -> Java Project.  Called it 'jtrek' and pointed the Location to where I downloaded jtrek from github (for me d:\projects\test\jtrek), and then clicked Finish.

This has 4 errors for me (looking at the Problems tab at the bottom), all dealing with the MigLayout library.  So, we need to specify our external dependencies.

In the Package Explorer, right-click on the top level 'jtrek' (project name) and click Properties.  Click 'Java Build Path', then on the 'Libraries' tab.  Click 'Add JARs...'  Select the 3 libraries there (although, I don't think groovy is used for anything yet) found in the jtrek/lib folder (also, if you're using postgres instead of mysql, you'll need to add the postgres jdbc driver JAR here instead of the mysql one) and click OK.  Click OK again to close the jtrek project properties window.

This cleared out the errors for me, so we're ready to start the server.  Let's create a 'runner'.  Go to menu Run -> Run Configurations.  Choose Java Application on the left, and above it click the 'New launch configuration' button.  Specify a name for the configuration 'jtrek server' (or whatever) and the main class, which is 'org.gamehost.jtrek.javatrek.TrekMain'.  Click the Arguments tab, and in VM arguments type, '-Xmx128m'  (without quotes) - this will limit jtrek to using 128 meg of RAM.  Then click Run at the bottom to start the server.  (I had already configured the jtrek.properties in the checkout folder, or else you'd need to do that before it would work properly.)  

The Console tab at the bottom will show the messages from the running jtrek server.

For subsequent runs, you won't need to repeat this configuration step, as it will already be created.  You'd instead just click the Play icon (or the little dropdown next to it) on the toolbar (below the Project menu on my screen), and select 'jtrek server'.

If you want to debug it (where you can set breakpoints, inspect variable values during runtime, etc), you can just start the server with the 'Debug' option instead of the 'Run' (using the same configuration created above).  The debug icon is just to the left (and looks like a bug) of the run icon.

That's about it!

**Comment by hsnewman** [comment]
This is awesome!  Just heads up, I've been writing a game simular to
decwar, which I love (see my webpage at:
http://hsnewman.freeshell.org/decwar.htm ).  I've been writing in C, but
hate how long it's taking and how brute force it is.  Seeing your code
looks so elegant, I'm thinking of starting over and using your code as a
template.

Thanks for the starter, it looks like a long learning curve ahead of me.
But having something to start with will be a big help.

If your ever interested in trying decwar, I can spin it up in an emulator
for the PDP10/Tops 10 ...I also released the source after it was lost for
about 20+ years, it's here:
http://repositories.lib.utexas.edu/handle/2152/11351

I'll likely have more questions down the road but this gives me somewhere
to start reading.
Harris

**Comment by hsnewman** [comment]
Jay, you mentioned that you don't use eclipse.  What do you use, and why?
Thanks,
Harris

**Comment by rumour** [comment]
I'm using IntelliJ IDEA - they have a community version that handles Java/Groovy/Scala/Android/etc. and an ultimate version that adds in Spring/Hibernate/JEE/etc support.

http://www.jetbrains.com/idea/download/index.html

I like Eclipse fine, but Jetbrains (maker of IDEA) used the tag line 'develop with pleasure' for a long time, and that's what programming in their IDE is like.  They just do a great job of showing the right information at the right time (via ctrl-space autocomplete, or whatever), quickly and easily navigating through your code, powerful refactoring abilities, and a pleasant experience to the eyeball (I like the new Darcula theme).  Eclipse does most of this stuff really well too, but it just isn't quite as seamless.  I think Eclipse does some things better, but my overall productivity is just better in IDEA.  Also, it has the best Groovy support, and that's what I'm spending a majority of my time doing now.  If you have a lot of experience with Eclipse, it may not be worth switching, but if you'd be new'ish to either, than I think it's definitely worth it to investigate it as an alternative.

This link details some points where others felt IntelliJ was strong:

http://programmers.stackexchange.com/questions/21987/how-is-intellij-better-than-eclipse
